# Generated by Django 4.1.2 on 2022-12-19 23:31

from django.db import migrations, models
import monitoramento_cpd_app.models.impressoras


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=30)),
                ('IP', models.CharField(max_length=255, unique=True, validators=[monitoramento_cpd_app.models.impressoras.validar_ip])),
                ('modelo', models.CharField(choices=[('Lexmark MS811', 'Lexmark MS811'), ('Lexmark MX611dhe', 'Lexmark MX611dhe'), ('M4206-MarkII', 'M4206-MarkII')], default='Lexmark MS811', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PDV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkout', models.CharField(max_length=255, unique=True)),
                ('IP', models.CharField(max_length=255, unique=True)),
                ('tipo_pdv', models.CharField(choices=[('Frente de caixa', 'Frente de caixa'), ('Cafeteria', 'Cafeteria')], default='Frente de caixa', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Thinclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255, unique=True)),
                ('sistema', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('IP', models.CharField(max_length=255, unique=True)),
                ('local', models.CharField(max_length=255)),
                ('dominio', models.CharField(max_length=255)),
                ('modelo', models.CharField(choices=[('Lenovo', 'Lenovo'), ('HP', 'HP')], default='Lenovo', max_length=255)),
            ],
        ),
    ]
