# Generated by Django 4.1.2 on 2022-12-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_cpd_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='conexao_pinpad',
            field=models.CharField(choices=[('USB', 'USB'), ('SERIAL', 'SERIAL')], default='SERIAL', max_length=255),
        ),
        migrations.AddField(
            model_name='pdv',
            name='num_serial_pinpad',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
