# Generated by Django 4.1.2 on 2022-12-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_cpd_app', '0002_pdv_conexao_pinpad_pdv_num_serial_pinpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='login_pdv',
            field=models.CharField(default='nulo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdv',
            name='porta_ssh_pdv',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdv',
            name='pwd_pdv',
            field=models.CharField(default='Nulo', max_length=255),
            preserve_default=False,
        ),
    ]
