# Generated by Django 4.1.2 on 2022-12-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_cpd_app', '0002_pdv_conexao_pinpad_pdv_num_serial_pinpad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='num_serial_pinpad',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
