# Generated by Django 4.1.2 on 2022-12-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_cpd_app', '0003_pdv_login_pdv_pdv_porta_ssh_pdv_pdv_pwd_pdv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdv',
            name='num_serial_pinpad',
        ),
    ]
